services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
    logging:
      driver: json-file
      options:
        max-size: 1m
  mongo1:
    image: mongo:7.0.5
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
    command:
      - mongod
      - --replSet
      - rs0
      - --keyFile
      - /secrets/rs0.key
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./secrets/rs0.key:/secrets/rs0.key
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /secrets/rs0.key
        chown 999:999 /secrets/rs0.key
        exec docker-entrypoint.sh $$@
  mongo2:
    image: mongo:7.0.5
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
    command:
      - mongod
      - --replSet
      - rs0
      - --keyFile
      - /secrets/rs0.key
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./secrets/rs0.key:/secrets/rs0.key
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /secrets/rs0.key
        chown 999:999 /secrets/rs0.key
        exec docker-entrypoint.sh $$@
  mongo3:
    image: mongo:7.0.5
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
    command:
      - mongod
      - --replSet
      - rs0
      - --keyFile
      - /secrets/rs0.key
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./secrets/rs0.key:/secrets/rs0.key
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /secrets/rs0.key
        chown 999:999 /secrets/rs0.key
        exec docker-entrypoint.sh $$@
