version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
    logging:
      driver: json-file
      options:
        max-size: 1m
  mongo:
    image: mongo:7.0.5
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: json-file
      options:
        max-size: 1m
