services:
  rabbitmq:
    image: rabbitmq:3.13.0-management-alpine
    container_name: rabbitmq-dev
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
